<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <!-- Это поможет избежать проблем, если разные модули используют разные версии NuGet пакетов -->
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <KarpikRepositoryRoot>$(MSBuildThisFileDirectory)</KarpikRepositoryRoot>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <KarpikModuleDependency>
            <Visible>false</Visible>
        </KarpikModuleDependency>
    </ItemDefinitionGroup>

    <!-- Применяем только если имя проекта НЕ содержит "Codegen" -->
    <ItemGroup Condition="  !$(MSBuildProjectName.Contains('Codegen'))                             AND                             !$(MSBuildProjectName.Contains('Karpik.Engine.Core'))                             AND                             !$(MSBuildProjectName.Contains('.Publish'))                             AND                             $(MSBuildProjectName.Contains('Karpik.Engine'))">

        <ProjectReference Include="$(KarpikRepositoryRoot)Network.Codegen\Network.Codegen\Network.Codegen.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>

        <ProjectReference Include="$(KarpikRepositoryRoot)StatAndAbilities.Codegen\StatAndAbilities.Codegen\StatAndAbilities.Codegen.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>

    </ItemGroup>

    <ItemGroup Condition="$(MSBuildProjectDirectory.StartsWith('$(MSBuildThisFileDirectory)Modules'))">

        <ProjectReference Include="$(KarpikRepositoryRoot)Karpik.Engine.Core.Generator\Karpik.Engine.Core.Codegen\Karpik.Engine.Core.Codegen.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>

        <ProjectReference Include="$(KarpikRepositoryRoot)Tools\StaticAnalyzer\StaticAnalyzer.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>

    </ItemGroup>

    <ItemGroup Condition="!$(MSBuildProjectName.Contains('Codegen'))">
        <ProjectReference Include="$(KarpikRepositoryRoot)Karpik.Content.Codegen/Karpik.Content.Codegen.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup Label="ProjectConfigurator">
        <KarpikModuleSelection Include="AssetManagement" Enabled="true" />
        <KarpikModuleSelection Include="DebugModule" Enabled="true" />
        <KarpikModuleSelection Include="ECS" Enabled="true" />
        <KarpikModuleSelection Include="Graphics" Enabled="true" Implementation="OpenGL" />
        <KarpikModuleSelection Include="Input" Enabled="true" />
        <KarpikModuleSelection Include="LoggerModule" Enabled="true" />
        <KarpikModuleSelection Include="Modding" Enabled="true" Implementation="Lua" />
        <KarpikModuleSelection Include="Network.Client" Enabled="true" Implementation="LiteNetLib" />
        <KarpikModuleSelection Include="Network.Server" Enabled="true" Implementation="LiteNetLib" />
        <KarpikModuleSelection Include="Network.Shared" Enabled="true" Implementation="LiteNetLib" />
        <KarpikModuleSelection Include="Physics2D" Enabled="true" Implementation="Aether2D" />
        <KarpikModuleSelection Include="Spatial2D" Enabled="true" />
        <KarpikModuleSelection Include="StatAndAbilities" Enabled="true" />
        <KarpikModuleSelection Include="Tween" Enabled="true" />
        <KarpikModuleSelection Include="UnsafeUtilities" Enabled="true" />
        <KarpikModuleSelection Include="Window" Enabled="true" Implementation="Sdl2" />
    </ItemGroup>
</Project>
