<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Karpik.Engine.Client.Graphics.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <None Update="Pressstart2p.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <KarpikModuleDependency Include="ECS" />
      <ProjectReference Include="..\..\..\..\Karpik.Engine.Core.Runner\Karpik.Engine.Core.Runner.csproj" />
      <KarpikModuleDependency Include="AssetManagement" />
      <KarpikModuleDependency Include="Window" />
      <ProjectReference Include="..\..\..\..\first-parties\Karpik.Jobs\Karpik.Jobs\Karpik.Jobs.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NeoVeldrid" />
      <PackageReference Include="NeoVeldrid.ImGui" />
      <PackageReference Include="NeoVeldrid.SPIRV" />
      <PackageReference Include="StbImageSharp" />
    </ItemGroup>

</Project>
