<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Karpik.Engine.Shared.Modding</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MoonSharp" />
    </ItemGroup>

    <ItemGroup>
      <KarpikModuleDependency Include="Modding" />
    </ItemGroup>

</Project>
