<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Karpik.Engine.Shared.Physics</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\first-parties\DragonECS.Karpik.Extensions\DragonECS.Karpik.Extensions.csproj" />
      <ProjectReference Include="..\..\..\..\third-parties\DragonECS\DragonECS.csproj" />
      <ProjectReference Include="..\..\..\..\Karpik.Engine.Core.Runner\Karpik.Engine.Core.Runner.csproj" />
      <KarpikModuleDependency Include="ECS" />
      <KarpikModuleDependency Include="Network.Shared" />
      <KarpikModuleDependency Include="Spatial2D" />
    </ItemGroup>
</Project>
