using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Karpik.Engine.Core.Codegen;

[Generator]
public sealed class EcsUpdateRegistryGenerator : IIncrementalGenerator
{
    private const string ISystemUpdateName = "Karpik.Engine.Core.ISystemUpdate";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        INamedTypeSymbol? systemUpdate = compilation.GetTypeByMetadataName(ISystemUpdateName);
        if (systemUpdate is null)
            return;

        var systems = new List<SystemMetadata>();
        foreach (INamedTypeSymbol type in GetAllTypes(compilation.Assembly.GlobalNamespace))
        {
            if (type.TypeKind != TypeKind.Class || type.IsAbstract || !ImplementsInterface(type, systemUpdate))
                continue;

            systems.Add(CreateSystemMetadata(type));
        }

        if (systems.Count == 0)
            return;

        systems.Sort(static (left, right) => string.CompareOrdinal(left.TypeName, right.TypeName));
        context.AddSource("EcsUpdateRegistry.g.cs", SourceText.From(GenerateSource(systems), Encoding.UTF8));
    }

    private static SystemMetadata CreateSystemMetadata(INamedTypeSymbol type)
    {
        var accesses = new List<ComponentAccessMetadata>();
        var orders = new List<SystemOrderMetadata>();
        bool isSequential = false;

        foreach (AttributeData attribute in type.GetAttributes())
        {
            INamedTypeSymbol? attributeType = attribute.AttributeClass;
            if (attributeType is null)
                continue;

            if (attributeType.Name == "SequentialSystemAttribute")
            {
                isSequential = true;
                continue;
            }

            if (attributeType.TypeArguments.Length != 1)
                continue;

            if (attributeType.Name == "ReadsAttribute")
            {
                accesses.Add(new ComponentAccessMetadata(
                    attributeType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    "global::Karpik.Engine.Shared.ECS.Scheduling.EcsAccessMode.Read"));
                continue;
            }

            if (attributeType.Name == "WritesAttribute")
            {
                accesses.Add(new ComponentAccessMetadata(
                    attributeType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    "global::Karpik.Engine.Shared.ECS.Scheduling.EcsAccessMode.Write"));
                continue;
            }

            if (attributeType.Name == "RunsAfterAttribute")
            {
                orders.Add(new SystemOrderMetadata(
                    attributeType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    "global::Karpik.Engine.Shared.ECS.Scheduling.EcsOrderKind.After"));
                continue;
            }

            if (attributeType.Name == "RunsBeforeAttribute")
            {
                orders.Add(new SystemOrderMetadata(
                    attributeType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    "global::Karpik.Engine.Shared.ECS.Scheduling.EcsOrderKind.Before"));
            }
        }

        return new SystemMetadata(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            SanitizeIdentifier(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)),
            isSequential,
            accesses,
            orders);
    }

    private static string GenerateSource(IReadOnlyList<SystemMetadata> systems)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Karpik.Engine.Shared.ECS.Scheduling.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal sealed class GeneratedEcsUpdateRegistryProvider : global::Karpik.Engine.Shared.ECS.Scheduling.IEcsUpdateRegistryProvider");
        source.AppendLine("    {");

        foreach (SystemMetadata system in systems)
        {
            AppendAccessArray(source, system);
            AppendOrderArray(source, system);
        }

        source.AppendLine("        private static readonly global::Karpik.Engine.Shared.ECS.Scheduling.EcsUpdateSystemDescriptor[] Systems =");
        source.AppendLine("        {");

        foreach (SystemMetadata system in systems)
        {
            source.AppendLine("            new global::Karpik.Engine.Shared.ECS.Scheduling.EcsUpdateSystemDescriptor(");
            source.AppendLine($"                typeof({system.TypeName}),");
            source.AppendLine($"                IsSequential: {system.IsSequential.ToString().ToLowerInvariant()},");
            source.AppendLine($"                {system.Identifier}Accesses,");
            source.AppendLine($"                {system.Identifier}Orders),");
        }

        source.AppendLine("        };");
        source.AppendLine();
        source.AppendLine("        public global::System.ReadOnlySpan<global::Karpik.Engine.Shared.ECS.Scheduling.EcsUpdateSystemDescriptor> GetUpdateSystems()");
        source.AppendLine("        {");
        source.AppendLine("            return Systems;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }

    private static void AppendAccessArray(StringBuilder source, SystemMetadata system)
    {
        source.AppendLine($"        private static readonly global::Karpik.Engine.Shared.ECS.Scheduling.EcsComponentAccessDescriptor[] {system.Identifier}Accesses =");
        source.AppendLine("        {");

        foreach (ComponentAccessMetadata access in system.Accesses)
        {
            source.AppendLine("            new global::Karpik.Engine.Shared.ECS.Scheduling.EcsComponentAccessDescriptor(");
            source.AppendLine($"                typeof({access.ComponentTypeName}),");
            source.AppendLine($"                {access.Mode}),");
        }

        source.AppendLine("        };");
        source.AppendLine();
    }

    private static void AppendOrderArray(StringBuilder source, SystemMetadata system)
    {
        source.AppendLine($"        private static readonly global::Karpik.Engine.Shared.ECS.Scheduling.EcsSystemOrderDescriptor[] {system.Identifier}Orders =");
        source.AppendLine("        {");

        foreach (SystemOrderMetadata order in system.Orders)
        {
            source.AppendLine("            new global::Karpik.Engine.Shared.ECS.Scheduling.EcsSystemOrderDescriptor(");
            source.AppendLine($"                typeof({order.TargetSystemTypeName}),");
            source.AppendLine($"                {order.Kind}),");
        }

        source.AppendLine("        };");
        source.AppendLine();
    }

    private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol interfaceSymbol)
    {
        foreach (INamedTypeSymbol iface in type.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, interfaceSymbol))
                return true;
        }

        return false;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
    {
        foreach (ISymbol member in root.GetMembers())
        {
            if (member is INamespaceSymbol namespaceSymbol)
            {
                foreach (INamedTypeSymbol type in GetAllTypes(namespaceSymbol))
                    yield return type;
            }
            else if (member is INamedTypeSymbol typeSymbol)
            {
                foreach (INamedTypeSymbol type in GetAllTypes(typeSymbol))
                    yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamedTypeSymbol root)
    {
        yield return root;

        foreach (INamedTypeSymbol nested in root.GetTypeMembers())
        {
            foreach (INamedTypeSymbol type in GetAllTypes(nested))
                yield return type;
        }
    }

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (char character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.ToString();
    }

    private sealed class SystemMetadata
    {
        public SystemMetadata(
            string typeName,
            string identifier,
            bool isSequential,
            IReadOnlyList<ComponentAccessMetadata> accesses,
            IReadOnlyList<SystemOrderMetadata> orders)
        {
            TypeName = typeName;
            Identifier = identifier;
            IsSequential = isSequential;
            Accesses = accesses;
            Orders = orders;
        }

        public string TypeName { get; }
        public string Identifier { get; }
        public bool IsSequential { get; }
        public IReadOnlyList<ComponentAccessMetadata> Accesses { get; }
        public IReadOnlyList<SystemOrderMetadata> Orders { get; }
    }

    private readonly struct ComponentAccessMetadata
    {
        public ComponentAccessMetadata(string componentTypeName, string mode)
        {
            ComponentTypeName = componentTypeName;
            Mode = mode;
        }

        public string ComponentTypeName { get; }
        public string Mode { get; }
    }

    private readonly struct SystemOrderMetadata
    {
        public SystemOrderMetadata(string targetSystemTypeName, string kind)
        {
            TargetSystemTypeName = targetSystemTypeName;
            Kind = kind;
        }

        public string TargetSystemTypeName { get; }
        public string Kind { get; }
    }
}
