using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Karpik.Engine.Core.Codegen;

[Generator]
public class ModuleRegistratorGenerator : IIncrementalGenerator
{
    private const string IModuleName = "Karpik.Engine.Core.IModule";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Нам нужна сама компиляция, чтобы искать типы во всех ссылках
        var compilationProvider = context.CompilationProvider;

        context.RegisterSourceOutput(compilationProvider, (spc, compilation) => { Execute(spc, compilation); });
    }

    private void Execute(SourceProductionContext context, Compilation compilation)
    {
        // 1. Находим символ интерфейса IModule
        var iModuleSymbol = compilation.GetTypeByMetadataName(IModuleName);
        if (iModuleSymbol == null)
        {
            // Если интерфейс не найден (странно, но бывает), ничего не делаем
            return;
        }

        var modulesToRegister = new List<string>();

        // 2. Сканируем саму текущую сборку (Launcher) и все референсы
        // ВАЖНО: Сканировать References может быть медленно на гигантских проектах.
        // Для оптимизации проверяем, ссылается ли сборка вообще на Engine.Core.

        var allAssemblies = new List<IAssemblySymbol> { compilation.Assembly };
        allAssemblies.AddRange(compilation.SourceModule.ReferencedAssemblySymbols);

        foreach (var assembly in allAssemblies)
        {
            // Пропускаем системные сборки для скорости
            if (IsSystemAssembly(assembly)) continue;

            // Ищем все типы в глобальном пространстве имен сборки (рекурсивно)
            var types = GetAllTypes(assembly.GlobalNamespace);

            foreach (var type in types)
            {
                // Проверяем:
                // - Это класс?
                // - Не абстрактный?
                // - Реализует IModule?
                if (type.TypeKind == TypeKind.Class &&
                    !type.IsAbstract &&
                    ImplementsInterface(type, iModuleSymbol))
                {
                    // Проверяем наличие пустого конструктора
                    if (HasParameterlessConstructor(type))
                    {
                        modulesToRegister.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    }
                }
            }
        }

        // 3. Генерируем код
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Karpik.Engine.Core;");
        sb.AppendLine();
        sb.AppendLine("namespace Karpik.Engine.Core");
        sb.AppendLine("{");
        sb.AppendLine("    public static class ModuleRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void RegisterAll(Bootstrap bootstrap)");
        sb.AppendLine("        {");

        foreach (var moduleClass in modulesToRegister)
        {
            // Генерируем: bootstrap.RegisterModule(new MyNamespace.MyModule());
            sb.AppendLine($"            bootstrap.RegisterModule(new {moduleClass}());");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ModuleRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // --- Helpers ---

    private bool IsSystemAssembly(IAssemblySymbol assembly)
    {
        var name = assembly.Name;
        return name.StartsWith("System") ||
               name.StartsWith("Microsoft") ||
               name.StartsWith("netstandard") ||
               name.StartsWith("mscorlib");
    }

    private bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol interfaceSymbol)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, interfaceSymbol))
                return true;
        }

        return false;
    }

    private bool HasParameterlessConstructor(INamedTypeSymbol type)
    {
        // Если конструкторов нет вообще - компилятор создает дефолтный
        if (type.Constructors.Length == 0) return true;

        // Ищем конструктор без параметров
        foreach (var ctor in type.Constructors)
        {
            if (ctor.Parameters.Length == 0 && !ctor.IsStatic && ctor.DeclaredAccessibility == Accessibility.Public)
                return true;
        }

        return false;
    }

    private IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
    {
        foreach (var member in root.GetMembers())
        {
            if (member is INamespaceSymbol namespaceSymbol)
            {
                foreach (var type in GetAllTypes(namespaceSymbol))
                    yield return type;
            }
            else if (member is INamedTypeSymbol typeSymbol)
            {
                yield return typeSymbol;
            }
        }
    }
}