<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Karpik.Engine.Shared.Log</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <KarpikModuleDependency Include="Karpik.Engine.Core.Runner" />
      <KarpikModuleDependency Include="Karpik.Engine.Core" />
      <KarpikModuleDependency Include="Karpik.Jobs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
    </ItemGroup>

</Project>
