<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Karpik.Engine.Shared.Modding</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\first-parties\Karpik.Jobs\Karpik.Jobs\Karpik.Jobs.csproj" />
      <KarpikModuleDependency Include="AssetManagement" />
      <KarpikModuleDependency Include="ECS" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

</Project>
