using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Network.Codegen;

internal static class CommandIdDebugger
{
    public static void GenerateDebugInfo(SourceProductionContext context, IEnumerable<string> allCommandNames)
    {
        var commandList = allCommandNames.ToList();
        if (!commandList.Any()) return;
        
        var allIds = commandList.ToDictionary(name => name, name => CommandIdManager.GetOrAssignId(name));

        // Группировка
        var stateCommands = allIds.Where(kvp => !kvp.Key.Contains(".") && kvp.Key.EndsWith("Command")).ToList();
        var targetRpcCommands = allIds.Where(kvp => kvp.Key.StartsWith("TargetRpc.")).ToList();
        var clientRpcCommands = allIds.Where(kvp => kvp.Key.StartsWith("ClientRpc.")).ToList();
        
        // Формирование списков строк
        string FormatGroup(List<KeyValuePair<string, uint>> group, string title)
        {
            if (!group.Any()) return "";
            var sb = new StringBuilder();
            sb.AppendLine($"{title}:");
            foreach (var cmd in group.OrderBy(kvp => kvp.Value))
                sb.AppendLine($"  ID {cmd.Value,3}: {cmd.Key}");
            return sb.ToString();
        }

        var stateStr = FormatGroup(stateCommands, "КОМАНДЫ ОТ КЛИЕНТА");
        var targetStr = FormatGroup(targetRpcCommands, "TARGET RPC КОМАНДЫ");
        var clientStr = FormatGroup(clientRpcCommands, "CLIENT RPC КОМАНДЫ");

        // Генерация констант
        var constantsSb = new StringBuilder();
        foreach (var cmd in allIds.OrderBy(kvp => kvp.Value))
        {
            var constantName = cmd.Key.Replace(".", "_").Replace(" ", "_").ToUpperInvariant();
            constantsSb.AppendLine($"        public const uint {constantName} = {cmd.Value};");
        }

        var source = $$"""
            // <auto-generated/>
            // Отладочная информация о назначенных ID команд
            
            /*
            НАЗНАЧЕННЫЕ ID КОМАНД:
            ======================

            {{stateStr}}
            {{targetStr}}
            {{clientStr}}

            ВСЕГО КОМАНД: {{allIds.Count}}
            */

            namespace Network.Generated
            {
                /// <summary>
                /// Константы ID команд для отладки
                /// </summary>
                internal static class CommandIds
                {
            {{constantsSb}}    }
            }
            """;

        context.AddSource("CommandIds.Debug.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    public static void ValidateCommandIds(SourceProductionContext context, IEnumerable<string> allCommandNames)
    {
        var collisions = CommandIdManager.CheckCollisions(allCommandNames);
        if (collisions.Any())
        {
            foreach (var collision in collisions)
            {
                var commands = string.Join(", ", collision.Value);
                var descriptor = new DiagnosticDescriptor(
                    "CMD001",
                    "Command ID collision detected",
                    $"Multiple commands have the same deterministic ID {collision.Key}: {commands}. Consider renaming one of the commands.",
                    "Commands",
                    DiagnosticSeverity.Warning,
                    true);
                context.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None));
            }
        }
    }
}