using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Network.Codegen;

[Generator]
public class NetworkGenerator : IIncrementalGenerator
{
    private const string NetworkedComponentAttribute = "Network.NetworkedComponentAttribute";
    private const string NetworkedFieldAttribute = "Network.NetworkedFieldAttribute";
    
    // Настройка: Где искать ваш ручной NetworkManager
    private const string NetworkManagerNamespace = "Karpik.Engine.MyGame.Shared.Main"; 
    private const string NetworkManagerClass = "NetworkManager";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }
    
    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        var projectType = ProjectTypeDetector.DetectProjectType(compilation.AssemblyName ?? "");
        if (projectType != ProjectTypeDetector.ProjectType.Shared) return;

        var structs = FindComponents(compilation, context.CancellationToken);
        context.AddSource("NetworkManager.g.cs", SourceText.From(GenerateSource(structs), Encoding.UTF8));
    }

    private static string GenerateSource(List<StructToGenerate> structs)
    {
        var reg = new StringBuilder();
        var write = new StringBuilder();
        var apply = new StringBuilder();
        var classes = new StringBuilder();
        long id = 1;

        foreach (var s in structs)
        {
            reg.AppendLine($"            _serializers.Add({id}, new {s.Name}Serializer());");
            
            write.AppendLine($$"""
                        var p{{id}} = world.GetPool<{{s.FullName}}>();
                        bool h{{id}} = p{{id}}.Has(entityId);
                        writer.Put(h{{id}});
                        if (h{{id}}) _serializers[{{id}}].Write(writer, p{{id}}.Get(entityId));
            """);

            apply.AppendLine($$"""
                        if (reader.GetBool()) _serializers[(long){{id}}].ReadAndApply(world, localEntityId, reader);
                        else world.GetPool<{{s.FullName}}>().TryDel(localEntityId);
            """);

            var wF = new StringBuilder();
            var rF = new StringBuilder();
            foreach(var f in s.Fields)
            {
                wF.AppendLine($"                writer.Put(c.{f.Name});");
                rF.AppendLine($"                c.{f.Name} = reader.Get{GetReaderMethod(f.TypeName)}();");
            }

            classes.AppendLine($$"""
                private class {{s.Name}}Serializer : IComponentSerializer {
                    public void Write(IWriter writer, object o) {
                        var c = ({{s.FullName}})o;
            {{wF}}        }
                    public void ReadAndApply(EcsWorld w, int e, IReader reader) {
                        ref var c = ref w.GetPool<{{s.FullName}}>().TryAddOrGet(e);
            {{rF}}        }
                    public void ClearPool(EcsWorld w) => w.GetPool<{{s.FullName}}>().ClearAll();
                }
            """);
            id++;
        }

        return $$"""
            // <auto-generated/>
            using DCFApixels.DragonECS;
            using System.Collections.Generic;
            using Karpik.Engine.Shared.Network.Core;

            namespace {{NetworkManagerNamespace}}
            {
                public partial class {{NetworkManagerClass}}
                {
                    private interface IComponentSerializer {
                        void Write(IWriter w, object o);
                        void ReadAndApply(EcsWorld w, int e, IReader r);
                        void ClearPool(EcsWorld w);
                    }
                    private class Aspect : EcsAspect { public EcsPool<NetworkId> networkId = Inc; }
                    
                    private readonly Dictionary<long, IComponentSerializer> _serializers = new();
                    private readonly Dictionary<int, int> _netToEnt = new();
                    private readonly Dictionary<int, int> _entToNet = new();

                    // Вызовите этот метод в Initialize() вашего класса!
                    private partial void RegisterSerializers() {
                        if(_serializers.Count > 0) return;
            {{reg}}        }

                    public partial void WriteSnapshot(EcsWorld world, IWriter writer, List<int> destroyed) {
                        writer.Put(destroyed.Count);
                        foreach(var id in destroyed) writer.Put(id);
                        
                        var ents = world.Where(out Aspect a);
                        writer.Put(ents.Count);
                        foreach(var entityId in ents) {
                            writer.Put(a.networkId.Get(entityId).Id);
            {{write}}            }
                    }

                    public partial void ApplySnapshot(EcsWorld world, IReader reader) {
                        int delCount = reader.GetInt();
                        for(int i=0; i<delCount; i++) {
                            int netId = reader.GetInt();
                            if(_netToEnt.TryGetValue(netId, out int ent)) {
                                if(world.GetEntityLong(ent).IsAlive) world.DelEntity(ent);
                                _netToEnt.Remove(netId); _entToNet.Remove(ent);
                            }
                        }
                        int count = reader.GetInt();
                        var pool = world.GetPool<NetworkId>();
                        for(int i=0; i<count; i++) {
                            int netId = reader.GetInt();
                            if(!_netToEnt.TryGetValue(netId, out int localEntityId)) {
                                localEntityId = world.NewEntity();
                                pool.Add(localEntityId).Id = netId;
                                _netToEnt[netId] = localEntityId; _entToNet[localEntityId] = netId;
                            }
            {{apply}}            }
                    }
                    public partial void ClearClientCache() { _netToEnt.Clear(); _entToNet.Clear(); }
            {{classes}}    }
            }
            """;
    }

    // --- Helpers ---
    private static List<StructToGenerate> FindComponents(Compilation c, CancellationToken ct)
    {
        var compAttr = c.GetTypeByMetadataName(NetworkedComponentAttribute);
        var fieldAttr = c.GetTypeByMetadataName(NetworkedFieldAttribute);
        if (compAttr == null) return new List<StructToGenerate>();

        var list = new List<StructToGenerate>();
        var asms = new[] { c.Assembly }.Concat(c.SourceModule.ReferencedAssemblySymbols);
        foreach(var asm in asms) ProcessNs(asm.GlobalNamespace, compAttr, fieldAttr, list, ct);
        return list.GroupBy(x => x.FullName).Select(x => x.First()).OrderBy(x => x.FullName).ToList();
    }

    private static void ProcessNs(INamespaceSymbol ns, ITypeSymbol cAttr, ITypeSymbol fAttr, List<StructToGenerate> list, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        foreach(var t in ns.GetTypeMembers()) {
            if(t.GetAttributes().Any(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, cAttr))) {
                var fields = new List<FieldToGenerate>();
                foreach(var m in t.GetMembers())
                    if(m is IFieldSymbol f && f.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, fAttr)))
                        fields.Add(new FieldToGenerate(f.Name, f.Type.ToDisplayString()));
                list.Add(new StructToGenerate(t.Name, t.ToDisplayString(), fields));
            }
        }
        foreach(var n in ns.GetNamespaceMembers()) ProcessNs(n, cAttr, fAttr, list, ct);
    }
    private static string GetReaderMethod(string t)
    {
        var last = t.Split('.').Last();
        return string.Concat(last[0].ToString().ToUpper(), last.Substring(1));
    }
}
internal record FieldToGenerate(string Name, string TypeName);
internal record StructToGenerate(string Name, string FullName, List<FieldToGenerate> Fields);