using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Network.Codegen;

[Generator]
public class RpcGenerator : IIncrementalGenerator
{
    // Маркерные интерфейсы (должны быть у вас в коде)
    private const string EventCommandInterface = "Karpik.Engine.Shared.Network.Core.IEventCommand";
    private const string StateCommandInterface = "Karpik.Engine.Shared.Network.Core.IStateCommand";

    // Match the engine-owned namespace used by the generated snapshot registry.
    private const string ServerDispatcherNamespace = "Karpik.Engine.Generated";
    private const string ServerDispatcherClass = "CommandDispatcher";

    // Настройка: Полное имя вашего ручного интерфейса IRpc
    private const string IRpcInterfaceFullName = "Karpik.Engine.Shared.Network.Core.IRpc";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var input = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(input, static (productionContext, pair) =>
            Execute(productionContext, pair.Left, pair.Right));
    }

    private static void Execute(
        SourceProductionContext context,
        Compilation compilation,
        AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!ProjectTypeDetector.TryGetProjectProperties(optionsProvider, context, out var properties) ||
            !properties.IsRuntime)
        {
            return;
        }

        var assemblyName = compilation.AssemblyName ?? "GeneratedAssembly";
        var safeAssemblyName = assemblyName.Replace(".", "_");
        var projectType = properties.Side;

        // 1. Ищем локальные команды (для генерации Extensions в текущем проекте)
        var localEvent = FindCommands(compilation, context.CancellationToken, EventCommandInterface, true);
        var localState = FindCommands(compilation, context.CancellationToken, StateCommandInterface, true);
        var localAll = localEvent.Concat(localState).ToList();

        // 2. Ищем ВСЕ команды (для генерации Dispatcher в ServerApp)
        var allEvent = FindCommands(compilation, context.CancellationToken, EventCommandInterface, false);
        var allState = FindCommands(compilation, context.CancellationToken, StateCommandInterface, false);
        var allTotal = allEvent.Concat(allState).ToList();

        // --- ГЕНЕРАЦИЯ ---

        // A. Requests (Структуры для State команд - всегда генерируем рядом)
        if (localState.Count != 0)
        {
            context.AddSource("CommandRequests.g.cs", SourceText.From(GenerateRequests(localState), Encoding.UTF8));
        }

        // B. Extensions (В ЛЮБОМ проекте). Позволяет писать _rpc.Command()
        if (localAll.Count != 0)
        {
            context.AddSource($"RpcExtensions_{safeAssemblyName}.g.cs", SourceText.From(GenerateExtensions(safeAssemblyName, localAll), Encoding.UTF8));
        }

        // C. Server Dispatcher (Только в ServerApp). Наполняет partial class.
        if (projectType == ProjectTypeDetector.ProjectType.Server && allTotal.Count != 0)
        {
            context.AddSource("ServerCommandDispatcher.g.cs", SourceText.From(GenerateServerDispatcher(allTotal), Encoding.UTF8));
        }
    }

    private static string GenerateRequests(List<CommandInfo> infos)
    {
        var sb = new StringBuilder();
        foreach (var cmd in infos)
        {
            var fields = new StringBuilder();
            foreach (var f in cmd.Fields.Where(x => x.Name != "Target" && x.Name != "Source"))
                fields.AppendLine($"        public {f.TypeName} {f.Name};");

            sb.AppendLine($$"""
                public struct {{cmd.Name}}Request : IEcsComponentRequest
                {
            {{fields}}        public int Target { get; set; }
                    public IEnumerable<int> Sources { get; set; }
                }
            """);
        }
        return $$"""
            // <auto-generated/>
            using System.Collections.Generic;
            using Karpik.Engine.Shared.DragonECS;
            {{sb}}
            """;
    }

    private static string GenerateExtensions(string safeAsmName, List<CommandInfo> infos)
    {
        var sb = new StringBuilder();
        foreach (var cmd in infos)
        {
            var paramName = cmd.Name.Replace("Command", "").ToLower();
            var methodName = cmd.Name.Replace("Command", "");
            
            var w = new StringBuilder();
            foreach (var f in cmd.Fields) w.AppendLine($"            writer.Put({paramName}.{f.Name});");

            sb.AppendLine($$"""
                    public static void {{methodName}}(this {{IRpcInterfaceFullName}} rpc, {{cmd.FullName}} {{paramName}}, DeliveryMethod deliveryMethod = DeliveryMethod.ReliableOrdered)
                    {
                        var writer = rpc.GetWriter();
                        writer.Reset();
                        writer.Put((byte)PacketType.Command);
                        writer.Put((ushort){{cmd.Id}});
            {{w}}            rpc.Send(deliveryMethod);
                    }
            """);
        }

        return $$"""
            // <auto-generated/>
            // Extensions generated for module: {{safeAsmName}}
            using Karpik.Engine.Shared.DragonECS;
            using Karpik.Engine.Shared.Network.Core;
            
            namespace Karpik.Engine.Shared.Extensions
            {
                public static class {{safeAsmName}}_RpcExtensions
                {
            {{sb}}    }
            }
            """;
    }

    private static string GenerateServerDispatcher(List<CommandInfo> infos)
    {
        var cases = new StringBuilder();
        foreach (var cmd in infos.OrderBy(x => x.Id))
        {
            var r = new StringBuilder();
            foreach (var f in cmd.Fields) r.AppendLine($"                    cmd.{f.Name} = reader.Get{GetReaderMethod(f.TypeName)}();");

            cases.AppendLine($$"""
                        case {{cmd.Id}}: // {{cmd.FullName}}
                        {
                            var cmd = new {{cmd.FullName}}();
            {{r}}                    _eventWorld.SendEvent(cmd);
                            break;
                        }
            """);
        }

        return $$"""
            // <auto-generated/>
            using Karpik.Engine.Shared;
            using Karpik.Engine.Core;
            using Karpik.Engine.Shared.DragonECS;
            using DCFApixels.DragonECS;
            using Karpik.Engine.Shared.Network.Core; // IReader

            namespace {{ServerDispatcherNamespace}}
            {
                public partial class {{ServerDispatcherClass}}
                {
                    private readonly EcsEventWorld _eventWorld;

                    public {{ServerDispatcherClass}}(EcsEventWorld eventWorld)
                    {
                        _eventWorld = eventWorld;
                    }

                    public void Dispatch(int playerEntity, IReader reader)
                    {
                        var commandId = reader.GetUShort();
                        switch (commandId)
                        {
            {{cases}}                default: break;
                        }
                    }
                }
            }
            """;
    }

    // --- Helpers ---
    private static List<CommandInfo> FindCommands(Compilation c, CancellationToken ct, string ifaceName, bool local)
    {
        var iface = c.GetTypeByMetadataName(ifaceName);
        if (iface == null) return new List<CommandInfo>();
        var list = new List<CommandInfo>();
        var asms = local ? new[] { c.Assembly } : new[] { c.Assembly }.Concat(c.SourceModule.ReferencedAssemblySymbols);
        foreach(var asm in asms) ProcessNs(asm.GlobalNamespace, iface, list, ct);
        var dist = list.GroupBy(x => x.FullName).Select(x => x.First()).OrderBy(x => x.FullName).ToList();
        for(int i=0; i<dist.Count; i++) dist[i] = dist[i] with { Id = CommandIdManager.GetOrAssignId(dist[i].FullName) };
        return dist;
    }
    private static void ProcessNs(INamespaceSymbol ns, INamedTypeSymbol iface, List<CommandInfo> list, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        foreach(var t in ns.GetTypeMembers()) {
            if(t.TypeKind == TypeKind.Struct && t.AllInterfaces.Contains(iface, SymbolEqualityComparer.Default)) {
                var f = t.GetMembers().OfType<IFieldSymbol>().Where(x=>!x.IsStatic && x.CanBeReferencedByName).Select(x=>new FieldInfo(x.Name, x.Type.ToDisplayString()));
                var p = t.GetMembers().OfType<IPropertySymbol>().Where(x=>!x.IsStatic && x.CanBeReferencedByName).Select(x=>new FieldInfo(x.Name, x.Type.ToDisplayString()));
                list.Add(new CommandInfo(0, t.Name, t.ToDisplayString(), f.Concat(p).ToList()));
            }
        }
        foreach(var n in ns.GetNamespaceMembers()) ProcessNs(n, iface, list, ct);
    }

    private static string GetReaderMethod(string t)
    {
        var last = t.Split('.').Last();
        return string.Concat(last[0].ToString().ToUpper(), last.Substring(1));
    }
}
internal record FieldInfo(string Name, string TypeName);

internal record CommandInfo(uint Id, string Name, string FullName, List<FieldInfo> Fields);
