using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Network.Codegen;

[Generator]
public class TargetClientRpcGenerator : IIncrementalGenerator
{
    private const string TargetRpcInterface = "Karpik.Engine.Shared.Network.Core.ITargetRpcCommand";
    private const string ClientRpcInterface = "Karpik.Engine.Shared.Network.Core.IClientRpcCommand";
    
    // Настройка: Где искать ваш ручной Dispatcher на клиенте
    private const string ClientDispatcherNamespace = "Karpik.Engine.MyGame.Client.Main";
    private const string ClientDispatcherClass = "TargetClientRpcDispatcher";

    // Настройка: Ваше имя интерфейса ITargetRpcSender
    private const string ISenderInterfaceFullName = "Karpik.Engine.Shared.Network.Core.ITargetRpcSender";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private void Execute(SourceProductionContext context, Compilation compilation)
    {
        var assemblyName = compilation.AssemblyName ?? "Shared";
        var safeAssemblyName = assemblyName.Replace(".", "_");
        var projectType = ProjectTypeDetector.DetectProjectType(assemblyName);

        // 1. Локальные команды (Extensions генерируем везде)
        var localTarget = FindCommands(compilation, context.CancellationToken, TargetRpcInterface, true);
        var localClient = FindCommands(compilation, context.CancellationToken, ClientRpcInterface, true);
        var localAll = localTarget.Concat(localClient).ToList();

        // 2. Все команды (Dispatcher генерируем только на Клиенте)
        var allTarget = FindCommands(compilation, context.CancellationToken, TargetRpcInterface, false);
        var allClient = FindCommands(compilation, context.CancellationToken, ClientRpcInterface, false);

        // A. Extensions (Везде)
        context.AddSource($"RpcSenderExtensions_{safeAssemblyName}.g.cs", SourceText.From(GenerateExtensions(safeAssemblyName, localTarget, localClient), Encoding.UTF8));

        // B. Client Dispatcher (Только ClientApp)
        if (projectType == ProjectTypeDetector.ProjectType.Client)
        {
            context.AddSource("TargetClientRpcDispatcher.g.cs", SourceText.From(GenerateClientDispatcher(allTarget, allClient), Encoding.UTF8));
        }
    }

    private string GenerateExtensions(string safeAsmName, List<CommandInfo> targetCmds, List<CommandInfo> clientCmds)
    {
        var sb = new StringBuilder();
        foreach (var cmd in targetCmds) sb.Append(GenerateMethod(cmd, "TargetRpc"));
        foreach (var cmd in clientCmds) sb.Append(GenerateMethod(cmd, "ClientRpc"));

        return $$"""
            // <auto-generated/>
            // Sender Extensions generated for: {{safeAsmName}}
            using Karpik.Engine.Shared.Network.Core;

            namespace Karpik.Engine.Server.Extensions
            {
                public static class {{safeAsmName}}_SenderExtensions
                {
            {{sb}}    }
            }
            """;
    }

    private string GenerateMethod(CommandInfo cmd, string prefix)
    {
        var paramName = cmd.Name.Replace(prefix, "").ToLower();
        var methodName = cmd.Name.Replace(prefix, "");
        
        var w = new StringBuilder();
        foreach (var f in cmd.Fields) w.AppendLine($"            writer.Put({paramName}.{f.Name});");

        // Расширяем ITargetRpcSender
        string baseMethod = $$"""
                    public static void {{methodName}}(this {{ISenderInterfaceFullName}} sender, IPeer targetPeer, {{cmd.FullName}} {{paramName}}, DeliveryMethod deliveryMethod = DeliveryMethod.ReliableOrdered)
                    {
                        var writer = sender.GetWriter();
                        writer.Reset();
                        writer.Put((byte)Karpik.Engine.Shared.Network.Core.PacketType.Command);
                        writer.Put((ushort){{cmd.Id}});
            {{w}}            targetPeer.Send(writer, deliveryMethod);
                    }
            """;

        if (prefix == "ClientRpc")
        {
             baseMethod += $$"""

                    public static void {{methodName}}All(this {{ISenderInterfaceFullName}} sender, {{cmd.FullName}} {{paramName}}, DeliveryMethod deliveryMethod = DeliveryMethod.ReliableOrdered)
                    {
                        var writer = sender.GetWriter();
                        writer.Reset();
                        writer.Put((byte)Karpik.Engine.Shared.Network.Core.PacketType.Command);
                        writer.Put((ushort){{cmd.Id}});
            {{w}}            sender.GetManager().SendToAll(writer, deliveryMethod);
                    }
            """;
        }
        return baseMethod;
    }

    private string GenerateClientDispatcher(List<CommandInfo> tCmds, List<CommandInfo> cCmds)
    {
        var cases = new StringBuilder();
        foreach (var cmd in tCmds.Concat(cCmds))
        {
            var r = new StringBuilder();
            foreach (var f in cmd.Fields) r.AppendLine($"                    cmd.{f.Name} = reader.Get{GetReaderMethod(f.TypeName)}();");
            
            cases.AppendLine($$"""
                        case {{cmd.Id}}: // {{cmd.FullName}}
                        {
                            var cmd = new {{cmd.FullName}}();
            {{r}}                    _eventWorld.SendEvent(cmd);
                            break;
                        }
            """);
        }

        return $$"""
            // <auto-generated/>
            using Karpik.Engine.Shared;
            using Karpik.Engine.Core;
            using Karpik.Engine.Shared.DragonECS;
            using DCFApixels.DragonECS;
            using Karpik.Engine.Shared.Network.Core; // IReader

            namespace {{ClientDispatcherNamespace}}
            {
                public partial class {{ClientDispatcherClass}}
                {
                    [DI] private EcsEventWorld _eventWorld;
            
                    public void Dispatch(IReader reader)
                    {
                        var commandId = reader.GetUShort();
                        switch (commandId)
                        {
            {{cases}}                default: break;
                        }
                    }
                }
            }
            """;
    }

    // --- Helpers --- (Копия из RpcGenerator)
    private List<CommandInfo> FindCommands(Compilation c, CancellationToken ct, string ifaceName, bool local)
    {
        var iface = c.GetTypeByMetadataName(ifaceName);
        if (iface == null) return [];
        var list = new List<CommandInfo>();
        var asms = local
            ? [c.Assembly]
            : new[] { c.Assembly }.Concat(c.SourceModule.ReferencedAssemblySymbols);
        foreach (var asm in asms)
        {
            ProcessNs(asm.GlobalNamespace, iface, list, ct);
        }
        
        var dist = list
            .GroupBy(x => x.FullName)
            .Select(x => x.First())
            .OrderBy(x => x.FullName)
            .ToList();
        for (int i = 0; i < dist.Count; i++)
        {
            dist[i] = dist[i] with
            {
                Id = CommandIdManager.GetOrAssignId((ifaceName.Contains("Target") ? "TargetRpc." : "ClientRpc.") +
                                                    dist[i].FullName)
            };
        }
        return dist;
    }

    private void ProcessNs(INamespaceSymbol ns, INamedTypeSymbol iface, List<CommandInfo> list, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        foreach (var t in ns.GetTypeMembers())
        {
            if (t.TypeKind == TypeKind.Struct && t.AllInterfaces.Contains(iface, SymbolEqualityComparer.Default))
            {
                var f = t.GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(x => !x.IsStatic && x.CanBeReferencedByName)
                    .Select(x => new FieldInfo(x.Name, x.Type.ToDisplayString()));
                list.Add(new CommandInfo(0, t.Name, t.ToDisplayString(), f.ToList()));
            }
        }

        foreach (var n in ns.GetNamespaceMembers()) ProcessNs(n, iface, list, ct);
    }

    private static string GetReaderMethod(string t)
    {
        var last = t.Split('.').Last();
        return string.Concat(last[0].ToString().ToUpper(), last.Substring(1));
    }
}