<Project Sdk="Karpik.Engine.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <KarpikProjectKind>Tool</KarpikProjectKind>
    <KarpikSide>Client</KarpikSide>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\KarpikGame.Launcher\EngineLauncher.cs" Link="EngineLauncher.cs" />
    <ProjectReference Include="..\KarpikGame.Client\KarpikGame.Client.csproj"
                      ReferenceOutputAssembly="false"
                      Private="false" />
  </ItemGroup>
</Project>
