<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\first-parties\Karpik.Jobs\Karpik.Jobs\Karpik.Jobs.csproj" />
      <ProjectReference Include="..\Karpik.Engine.Core\Karpik.Engine.Core.csproj" />
      <ProjectReference Include="..\third-parties\DragonECS\DragonECS.csproj" />
    </ItemGroup>

</Project>
