using System.Text;
using System.Xml.Linq;

namespace ProjectConfigurator;

public static class ArtifactGenerator
{
    public static IReadOnlyDictionary<string, string> BuildArtifacts(RepositoryModel model, GraphResult graph)
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            [Path.Combine(model.RootPath, "AutoGenerated.targets")] = BuildTargets(model, graph),
            [Path.Combine(model.RootPath, "Generated", "KarpikModuleCatalog.props")] = BuildCatalog(model),
            [Path.Combine(model.RootPath, "Generated", "ModuleLoader.cs")] = BuildLoader(graph)
        };
    }

    public static void WriteArtifacts(IReadOnlyDictionary<string, string> artifacts)
    {
        foreach (var artifact in artifacts)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(artifact.Key)!);
            File.WriteAllText(artifact.Key, artifact.Value, new UTF8Encoding(false));
        }
    }

    private static string BuildCatalog(RepositoryModel model)
    {
        var projects = model.ProjectsByPath.Values
            .Select(project => (Id: project.PluginId, project.RelativePath))
            .Concat(model.Plugins
                .Where(plugin => plugin.Kind == PluginKind.Core)
                .Select(plugin => (Id: plugin.ModuleId, plugin.Project.RelativePath)))
            .Distinct()
            .OrderBy(project => project.Id, StringComparer.Ordinal)
            .ToList();
        var group = new XElement("ItemGroup");
        foreach (var project in projects)
        {
            group.Add(new XElement("KarpikModuleDependency",
                new XAttribute("Update", project.Id),
                new XElement("ResolvedProjectPath",
                    $"$(MSBuildThisFileDirectory)..\\{project.RelativePath.Replace('/', '\\')}")));
        }
        return new XDocument(new XDeclaration("1.0", "utf-8", null), new XElement("Project", group))
            .ToString() + Environment.NewLine;
    }

    private static string BuildTargets(RepositoryModel model, GraphResult graph)
    {
        XNamespace ns = "http://schemas.microsoft.com/developer/msbuild/2003";
        var project = new XElement(ns + "Project");
        var references = new XElement(ns + "ItemGroup");
        project.Add(references);

        foreach (var plugin in graph.ActivePlugins.OrderBy(plugin => plugin.Project.PluginId, StringComparer.Ordinal))
        {
            references.Add(CreateReference(ns, plugin.Project));
        }
        foreach (var root in model.GameRoots.OrderBy(project => project.PluginId, StringComparer.Ordinal))
        {
            references.Add(CreateReference(ns, root));
        }

        return new XDocument(new XDeclaration("1.0", "utf-8", null), project)
            .ToString() + Environment.NewLine;
    }

    private static XElement CreateReference(XNamespace ns, ProjectInfo project)
    {
        var element = new XElement(ns + "PluginReference",
            new XAttribute("Include", $"$(MSBuildThisFileDirectory){project.RelativePath}"));
        if (project.Side == ProjectSide.Client)
        {
            element.Add(new XAttribute("Condition", "'$(IsClient)' == 'true'"));
        }
        else if (project.Side == ProjectSide.Server)
        {
            element.Add(new XAttribute("Condition", "'$(IsServer)' == 'true'"));
        }
        return element;
    }

    private static string BuildLoader(GraphResult graph)
    {
        var shared = graph.ClientLoadOrder
            .Where(project => project.Side == ProjectSide.Shared)
            .Select(project => project.PluginId)
            .ToList();
        var client = graph.ClientLoadOrder
            .Where(project => project.Side == ProjectSide.Client)
            .Select(project => project.PluginId)
            .ToList();
        var server = graph.ServerLoadOrder
            .Where(project => project.Side == ProjectSide.Server)
            .Select(project => project.PluginId)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Karpik.Engine.Core.ModuleManagement;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine();
        sb.AppendLine("public sealed class ModuleLoader");
        sb.AppendLine("{");
        sb.AppendLine("    public readonly record struct PluginDescriptor(string AssemblyName, string Side);");
        sb.AppendLine("    public Assembly[] LoadedAssemblies = [];");
        sb.AppendLine("    private PluginLoadContext? _loadContext;");
        sb.AppendLine("    private string? _shadowCopyDirectory;");
        sb.AppendLine();
        AppendArray(sb, "Shared", shared);
        AppendArray(sb, "ClientOnly", client);
        AppendArray(sb, "ServerOnly", server);
        AppendDescriptors(sb, "Client", shared.Select(name => (name, "Shared")).Concat(client.Select(name => (name, "Client"))));
        AppendDescriptors(sb, "Server", shared.Select(name => (name, "Shared")).Concat(server.Select(name => (name, "Server"))));
        sb.AppendLine();
        sb.AppendLine("    public void LoadClientModules() => LoadPluginCollection(ClientModules.Select(module => module.AssemblyName));");
        sb.AppendLine("    public void LoadServerModules() => LoadPluginCollection(ServerModules.Select(module => module.AssemblyName));");
        sb.AppendLine();
        sb.AppendLine("    public void LoadPluginCollection(IEnumerable<string> assemblyNames)");
        sb.AppendLine("    {");
        sb.AppendLine("        var sourceDirectory = Path.Combine(AppContext.BaseDirectory, \"modules\");");
        sb.AppendLine("        if (!Directory.Exists(sourceDirectory))");
        sb.AppendLine("            throw new DirectoryNotFoundException($\"Module staging directory was not found: {sourceDirectory}. Build the launcher project before starting the worker.\");");
        sb.AppendLine("        var shadowRoot = Path.Combine(AppContext.BaseDirectory, \"reload\", \"shadow\");");
        sb.AppendLine("        _shadowCopyDirectory = Path.Combine(shadowRoot, $\"{Environment.ProcessId}_{Guid.NewGuid():N}\");");
        sb.AppendLine("        Directory.CreateDirectory(_shadowCopyDirectory);");
        sb.AppendLine("        CopyDirectory(sourceDirectory, _shadowCopyDirectory);");
        sb.AppendLine("        var requiredAssemblies = assemblyNames.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();");
        sb.AppendLine("        var missing = requiredAssemblies.Where(name => !File.Exists(Path.Combine(_shadowCopyDirectory, name + \".dll\"))).ToArray();");
        sb.AppendLine("        if (missing.Length > 0)");
        sb.AppendLine("            throw new FileNotFoundException($\"Required module assemblies are missing from {sourceDirectory}: {string.Join(\", \", missing)}. Build the matching ClientLauncher or ServerLauncher project.\");");
        sb.AppendLine("        _loadContext = new PluginLoadContext(_shadowCopyDirectory);");
        sb.AppendLine("        var loaded = new List<Assembly>(requiredAssemblies.Length);");
        sb.AppendLine("        foreach (var name in requiredAssemblies)");
        sb.AppendLine("            loaded.Add(_loadContext.LoadFromAssemblyPath(Path.Combine(_shadowCopyDirectory, name + \".dll\")));");
        sb.AppendLine("        LoadedAssemblies = loaded.ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void CopyDirectory(string sourceDirectory, string destinationDirectory)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var directory in Directory.GetDirectories(sourceDirectory, \"*\", SearchOption.AllDirectories))");
        sb.AppendLine("            Directory.CreateDirectory(Path.Combine(destinationDirectory, Path.GetRelativePath(sourceDirectory, directory)));");
        sb.AppendLine("        foreach (var file in Directory.GetFiles(sourceDirectory, \"*\", SearchOption.AllDirectories))");
        sb.AppendLine("        {");
        sb.AppendLine("            var destination = Path.Combine(destinationDirectory, Path.GetRelativePath(sourceDirectory, file));");
        sb.AppendLine("            Directory.CreateDirectory(Path.GetDirectoryName(destination)!);");
        sb.AppendLine("            File.Copy(file, destination, overwrite: true);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendArray(StringBuilder sb, string name, IEnumerable<string> assemblies)
    {
        sb.AppendLine($"    public readonly string[] {name}Assemblies =");
        sb.AppendLine("    {");
        foreach (var assembly in assemblies)
        {
            sb.AppendLine($"        \"{assembly}\",");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void AppendDescriptors(StringBuilder sb, string name, IEnumerable<(string Assembly, string Side)> modules)
    {
        sb.AppendLine($"    public readonly PluginDescriptor[] {name}Modules =");
        sb.AppendLine("    {");
        foreach (var module in modules)
        {
            sb.AppendLine($"        new(\"{module.Assembly}\", \"{module.Side}\"),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
    }
}
