using System.Text;
using System.Xml.Linq;

namespace ProjectConfigurator;

public static class ArtifactGenerator
{
    public static IReadOnlyDictionary<string, string> BuildArtifacts(RepositoryModel model, GraphResult graph)
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            [Path.Combine(model.RootPath, "AutoGenerated.targets")] = BuildTargets(model, graph),
            [Path.Combine(model.RootPath, "Generated", "KarpikModuleCatalog.props")] = BuildCatalog(model),
            [Path.Combine(model.RootPath, "Generated", "ModuleLoader.cs")] = BuildLoader(graph)
        };
    }

    public static void WriteArtifacts(IReadOnlyDictionary<string, string> artifacts)
    {
        foreach (var artifact in artifacts)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(artifact.Key)!);
            File.WriteAllText(artifact.Key, artifact.Value, new UTF8Encoding(false));
        }
    }

    private static string BuildCatalog(RepositoryModel model)
    {
        var modulePaths = model.Plugins
            .Select(plugin => plugin.Project.AbsolutePath)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        var projects = model.Plugins
            .Select(plugin => (Id: plugin.Project.PluginId, plugin.Project.RelativePath))
            .Concat(model.ProjectAliases
                .Where(alias => modulePaths.Contains(alias.Value.AbsolutePath))
                .Select(alias => (Id: alias.Key, alias.Value.RelativePath)))
            .Concat(model.Plugins
                .Where(plugin => plugin.Kind == PluginKind.Core)
                .Select(plugin => (Id: plugin.ModuleId, plugin.Project.RelativePath)))
            .Distinct()
            .OrderBy(project => project.Id, StringComparer.Ordinal)
            .ToList();
        var group = new XElement("ItemGroup");
        foreach (var project in projects)
        {
            group.Add(new XElement("KarpikModuleDependency",
                new XAttribute("Update", project.Id),
                new XElement("ResolvedProjectPath",
                    $"$(MSBuildThisFileDirectory)..\\{project.RelativePath.Replace('/', '\\')}")));
        }
        return new XDocument(new XDeclaration("1.0", "utf-8", null), new XElement("Project", group))
            .ToString() + Environment.NewLine;
    }

    private static string BuildTargets(RepositoryModel model, GraphResult graph)
    {
        XNamespace ns = "http://schemas.microsoft.com/developer/msbuild/2003";
        var project = new XElement(ns + "Project");
        var references = new XElement(ns + "ItemGroup");
        project.Add(references);

        foreach (var plugin in graph.ActivePlugins.OrderBy(plugin => plugin.Project.PluginId, StringComparer.Ordinal))
        {
            references.Add(CreateReference(ns, plugin.Project));
        }
        return new XDocument(new XDeclaration("1.0", "utf-8", null), project)
            .ToString() + Environment.NewLine;
    }

    private static XElement CreateReference(XNamespace ns, ProjectInfo project)
    {
        var element = new XElement(ns + "PluginReference",
            new XAttribute("Include", $"$(MSBuildThisFileDirectory){project.RelativePath}"));
        if (project.Side == ProjectSide.Client)
        {
            element.Add(new XAttribute("Condition", "'$(IsClient)' == 'true'"));
        }
        else if (project.Side == ProjectSide.Server)
        {
            element.Add(new XAttribute("Condition", "'$(IsServer)' == 'true'"));
        }
        return element;
    }

    private static string BuildLoader(GraphResult graph)
    {
        var shared = graph.ClientLoadOrder
            .Where(project => project.Side == ProjectSide.Shared)
            .Select(project => project.PluginId)
            .ToList();
        var client = graph.ClientLoadOrder
            .Where(project => project.Side == ProjectSide.Client)
            .Select(project => project.PluginId)
            .ToList();
        var server = graph.ServerLoadOrder
            .Where(project => project.Side == ProjectSide.Server)
            .Select(project => project.PluginId)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Karpik.Engine.Core;");
        sb.AppendLine("using Karpik.Engine.Core.ModuleManagement;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class ModuleLoader : IDisposable");
        sb.AppendLine("{");
        sb.AppendLine("    public string ModuleDirectory { get; private set; } = string.Empty;");
        sb.AppendLine("    public string ShadowCopyDirectory => _shadowCopyDirectory ?? string.Empty;");
        sb.AppendLine();
        sb.AppendLine("    public readonly record struct PluginDescriptor(string AssemblyName, string Side);");
        sb.AppendLine("    public Assembly[] LoadedAssemblies = [];");
        sb.AppendLine("    private PluginLoadContext? _loadContext;");
        sb.AppendLine("    internal WeakReference? LoadContextLifetime { get; private set; }");
        sb.AppendLine("    private string? _shadowCopyDirectory;");
        sb.AppendLine("    private readonly string? _bundleRoot;");
        sb.AppendLine("    private static readonly object DisposedShadowLock = new();");
        sb.AppendLine("    private static readonly List<(WeakReference Lifetime, string BundleRoot, string ShadowDirectory)> DisposedShadows = [];");
        sb.AppendLine();
        sb.AppendLine("    [Obsolete(\"Legacy monorepository compatibility only. External runners must provide an explicit bundle root.\")]");
        sb.AppendLine("    public ModuleLoader() { }");
        sb.AppendLine();
        sb.AppendLine("    public ModuleLoader(string bundleRoot)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(bundleRoot) || !Path.IsPathFullyQualified(bundleRoot))");
        sb.AppendLine("            throw new ArgumentException(\"Bundle root must be absolute.\", nameof(bundleRoot));");
        sb.AppendLine("        _bundleRoot = Path.GetFullPath(bundleRoot).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);");
        sb.AppendLine("    }");
        sb.AppendLine();
        AppendArray(sb, "Shared", shared);
        AppendArray(sb, "ClientOnly", client);
        AppendArray(sb, "ServerOnly", server);
        AppendDescriptors(sb, "Client", shared.Select(name => (name, "Shared")).Concat(client.Select(name => (name, "Client"))));
        AppendDescriptors(sb, "Server", shared.Select(name => (name, "Shared")).Concat(server.Select(name => (name, "Server"))));
        sb.AppendLine();
        sb.AppendLine("    public void LoadClientModules() => LoadPluginCollection(ClientModules.Select(module => module.AssemblyName));");
        sb.AppendLine("    public void LoadServerModules() => LoadPluginCollection(ServerModules.Select(module => module.AssemblyName));");
        sb.AppendLine();
        sb.AppendLine("    public void LoadPluginCollection(IEnumerable<string> assemblyNames)");
        sb.AppendLine("    {");
        sb.AppendLine("        var sourceDirectory = ResolveModuleDirectory();");
        sb.AppendLine("        ModuleDirectory = sourceDirectory;");
        sb.AppendLine("        if (!Directory.Exists(sourceDirectory))");
        sb.AppendLine("            throw new DirectoryNotFoundException($\"No completed module staging directory was found at: {sourceDirectory}. Build the selected first-party module set or use the installed side runner.\");");
        sb.AppendLine("        var manifestFiles = _bundleRoot is null ? null : RuntimeBundleLayout.ReadCanonicalModuleManifest(sourceDirectory);");
        sb.AppendLine("        var requiredAssemblies = ResolveAssemblyNames(manifestFiles, assemblyNames);");
        sb.AppendLine("        var shadowRoot = Path.Combine(_bundleRoot ?? AppContext.BaseDirectory, \"reload\", \"shadow\");");
        sb.AppendLine("        _shadowCopyDirectory = Path.Combine(shadowRoot, $\"{Environment.ProcessId}_{Guid.NewGuid():N}\");");
        sb.AppendLine("        Directory.CreateDirectory(_shadowCopyDirectory);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            CopyDirectory(sourceDirectory, _shadowCopyDirectory, manifestFiles);");
        sb.AppendLine("            var missing = requiredAssemblies.Where(name => !File.Exists(Path.Combine(_shadowCopyDirectory, name + \".dll\"))).ToArray();");
        sb.AppendLine("            if (missing.Length > 0)");
        sb.AppendLine("                throw new FileNotFoundException($\"Required module assemblies are missing from {sourceDirectory}: {string.Join(\", \", missing)}. Build the selected first-party module set or use the installed side runner.\");");
        sb.AppendLine("            _loadContext = CreateLoadContext(_shadowCopyDirectory);");
        sb.AppendLine("            LoadedAssemblies = LoadComposedAssemblies(requiredAssemblies);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_loadContext is null && _bundleRoot is not null)");
        sb.AppendLine("                TryDeleteOwnedShadowDirectory(_bundleRoot, _shadowCopyDirectory);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private string ResolveModuleDirectory()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_bundleRoot is not null)");
        sb.AppendLine("            return RuntimeBundleLayout.ResolveModuleDirectory(_bundleRoot);");
        sb.AppendLine("        string baseDirectory = AppContext.BaseDirectory;");
        sb.AppendLine("        string? latestCompleteDirectory = Directory");
        sb.AppendLine("            .GetDirectories(baseDirectory, \"modules.version.*\", SearchOption.TopDirectoryOnly)");
        sb.AppendLine("            .Where(directory => File.Exists(Path.Combine(directory, \".complete\")))");
        sb.AppendLine("            .OrderByDescending(directory => File.GetLastWriteTimeUtc(Path.Combine(directory, \".complete\")))");
        sb.AppendLine("            .FirstOrDefault();");
        sb.AppendLine("        return latestCompleteDirectory ?? Path.Combine(baseDirectory, \"modules\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string[] ResolveAssemblyNames(string[]? manifestFiles, IEnumerable<string> legacyAssemblyNames)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (manifestFiles is null)");
        sb.AppendLine("            return legacyAssemblyNames.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();");
        sb.AppendLine("        return manifestFiles");
        sb.AppendLine("            .Select(name => Path.GetFileNameWithoutExtension(name)!)");
        sb.AppendLine("            .ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void CopyDirectory(string sourceDirectory, string destinationDirectory, string[]? manifestFiles)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (manifestFiles is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            CopyLegacyDirectory(sourceDirectory, destinationDirectory);");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine("        foreach (var fileName in manifestFiles)");
        sb.AppendLine("            File.Copy(Path.Combine(sourceDirectory, fileName), Path.Combine(destinationDirectory, fileName), overwrite: false);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void CopyLegacyDirectory(string sourceDirectory, string destinationDirectory)");
        sb.AppendLine("    {");
        sb.AppendLine("        var pending = new Stack<(string Source, string Destination, int Depth)>();");
        sb.AppendLine("        pending.Push((sourceDirectory, destinationDirectory, 0));");
        sb.AppendLine("        var entries = 0;");
        sb.AppendLine("        long totalBytes = 0;");
        sb.AppendLine("        while (pending.Count > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            var current = pending.Pop();");
        sb.AppendLine("            foreach (var entry in Directory.EnumerateFileSystemEntries(current.Source))");
        sb.AppendLine("            {");
        sb.AppendLine("                if (++entries > RuntimeBundleLayout.MaxTreeEntries || (File.GetAttributes(entry) & FileAttributes.ReparsePoint) != 0)");
        sb.AppendLine("                    throw new InvalidDataException(\"Legacy module shadow copy exceeds entry bounds or contains a link.\");");
        sb.AppendLine("                var destination = Path.Combine(current.Destination, Path.GetFileName(entry));");
        sb.AppendLine("                if (Directory.Exists(entry))");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (current.Depth + 1 > RuntimeBundleLayout.MaxTreeDepth)");
        sb.AppendLine("                        throw new InvalidDataException(\"Legacy module shadow copy exceeds depth bounds.\");");
        sb.AppendLine("                    Directory.CreateDirectory(destination);");
        sb.AppendLine("                    pending.Push((entry, destination, current.Depth + 1));");
        sb.AppendLine("                    continue;");
        sb.AppendLine("                }");
        sb.AppendLine("                var length = new FileInfo(entry).Length;");
        sb.AppendLine("                if (length > RuntimeBundleLayout.MaxIndividualFileBytes || totalBytes > RuntimeBundleLayout.MaxBundleBytes - length)");
        sb.AppendLine("                    throw new InvalidDataException(\"Legacy module shadow copy exceeds byte bounds.\");");
        sb.AppendLine("                totalBytes += length;");
        sb.AppendLine("                File.Copy(entry, destination, overwrite: false);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");
        sb.AppendLine("        LoadContextLifetime = UnloadContext();");
        sb.AppendLine("        if (LoadContextLifetime is not null && _bundleRoot is not null && _shadowCopyDirectory is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            lock (DisposedShadowLock)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (DisposedShadows.Count < 256)");
        sb.AppendLine("                    DisposedShadows.Add((LoadContextLifetime, _bundleRoot, _shadowCopyDirectory));");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.NoInlining)]");
        sb.AppendLine("    private WeakReference? UnloadContext()");
        sb.AppendLine("    {");
        sb.AppendLine("        LoadedAssemblies = [];");
        sb.AppendLine("        if (_loadContext is null)");
        sb.AppendLine("            return null;");
        sb.AppendLine("        var lifetime = new WeakReference(_loadContext);");
        sb.AppendLine("        _loadContext.Unload();");
        sb.AppendLine("        _loadContext = null;");
        sb.AppendLine("        return lifetime;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.NoInlining)]");
        sb.AppendLine("    public static void CleanupDisposedShadows()");
        sb.AppendLine("    {");
        sb.AppendLine("        for (var attempt = 0; attempt < 10; attempt++)");
        sb.AppendLine("        {");
        sb.AppendLine("            GC.Collect();");
        sb.AppendLine("            GC.WaitForPendingFinalizers();");
        sb.AppendLine("            lock (DisposedShadowLock)");
        sb.AppendLine("                if (DisposedShadows.All(item => !item.Lifetime.IsAlive))");
        sb.AppendLine("                    break;");
        sb.AppendLine("        }");
        sb.AppendLine("        lock (DisposedShadowLock)");
        sb.AppendLine("        {");
        sb.AppendLine("            for (var index = DisposedShadows.Count - 1; index >= 0; index--)");
        sb.AppendLine("            {");
        sb.AppendLine("                var item = DisposedShadows[index];");
        sb.AppendLine("                if (item.Lifetime.IsAlive)");
        sb.AppendLine("                    continue;");
        sb.AppendLine("                TryDeleteOwnedShadowDirectory(item.BundleRoot, item.ShadowDirectory);");
        sb.AppendLine("                DisposedShadows.RemoveAt(index);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void TryDeleteOwnedShadowDirectory(string bundleRoot, string shadowCopyDirectory)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!Directory.Exists(shadowCopyDirectory))");
        sb.AppendLine("            return;");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var shadowRoot = Path.GetFullPath(Path.Combine(bundleRoot, \"reload\", \"shadow\")).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);");
        sb.AppendLine("            var owned = Path.GetFullPath(shadowCopyDirectory).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);");
        sb.AppendLine("            var comparison = OperatingSystem.IsWindows() ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;");
        sb.AppendLine("            if (!string.Equals(Path.GetDirectoryName(owned), shadowRoot, comparison))");
        sb.AppendLine("                return;");
        sb.AppendLine("            var entryCount = 0;");
        sb.AppendLine("            foreach (var entry in Directory.EnumerateFileSystemEntries(owned, \"*\", SearchOption.TopDirectoryOnly))");
        sb.AppendLine("                if (++entryCount > RuntimeBundleLayout.MaxManifestEntries || Directory.Exists(entry) || (File.GetAttributes(entry) & FileAttributes.ReparsePoint) != 0)");
        sb.AppendLine("                    return;");
        sb.AppendLine("            Directory.Delete(owned, recursive: true);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)");
        sb.AppendLine("        {");
        sb.AppendLine("            // ProcessManager performs defense-in-depth cleanup when a worker exits.");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendArray(StringBuilder sb, string name, IEnumerable<string> assemblies)
    {
        sb.AppendLine($"    public readonly string[] {name}Assemblies =");
        sb.AppendLine("    {");
        foreach (var assembly in assemblies)
        {
            sb.AppendLine($"        \"{assembly}\",");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void AppendDescriptors(StringBuilder sb, string name, IEnumerable<(string Assembly, string Side)> modules)
    {
        sb.AppendLine($"    public readonly PluginDescriptor[] {name}Modules =");
        sb.AppendLine("    {");
        foreach (var module in modules)
        {
            sb.AppendLine($"        new(\"{module.Assembly}\", \"{module.Side}\"),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
    }
}
