using System.Xml.Linq;

namespace Configurator;

// --- МОДЕЛЬ ДАННЫХ ---
public class ModuleInfo
{
    public string Name { get; set; } = "";
    public bool IsEnabled { get; set; } = true;
    public string SelectedImplementation { get; set; } = "";
    
    // Путь к Core проекту (если есть)
    public string? CorePath { get; set; }
    
    // Список доступных реализаций и пути к ним
    public List<string> Implementations { get; set; } = new();
    public Dictionary<string, string> ImplementationPaths { get; set; } = new();
}

class Program
{
    // Метка, чтобы не трогать ручные настройки пользователя в props файле
    const string CONFIG_LABEL = "ProjectConfigurator";

    static void Main(string[] args)
    {
        // 1. Ищем корень (где лежит .slnx)
        var rootPath = FindSolutionRoot(Directory.GetCurrentDirectory());
        if (rootPath == null)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("Ошибка: Файл .slnx не найден в текущей или родительских папках.");
            return;
        }

        var slnxPath = Directory.GetFiles(rootPath, "*.slnx").FirstOrDefault();
        var propsPath = Path.Combine(rootPath, "Directory.Build.props");

        if (slnxPath == null)
        {
            Console.WriteLine("Не найден файл .slnx!");
            return;
        }

        // 2. Сканируем решение
        var modules = ScanSlnx(slnxPath);

        // 3. Загружаем сохраненные настройки
        LoadConfig(propsPath, modules);

        // 4. Запускаем UI
        RunUI(modules, slnxPath, propsPath, rootPath);
    }

    // --- ЛОГИКА СКАНИРОВАНИЯ ---
    static List<ModuleInfo> ScanSlnx(string slnxPath)
    {
        var doc = XDocument.Load(slnxPath);
        var dict = new Dictionary<string, ModuleInfo>();

        var projects = doc.Descendants("Project")
            .Select(p => p.Attribute("Path")?.Value)
            .Where(p => !string.IsNullOrEmpty(p));

        foreach (var rawPath in projects)
        {
            string path = rawPath!.Replace('\\', '/');

            // СКАНИРУЕМ ТОЛЬКО ПАПКУ MODULES (Для UI)
            if (!path.StartsWith("Modules/", StringComparison.OrdinalIgnoreCase)) continue;

            var fileName = Path.GetFileNameWithoutExtension(path); 
            var parts = fileName.Split('.');

            if (parts.Length < 2) continue;

            string impl = parts.Last();
            string moduleName = string.Join(".", parts.Take(parts.Length - 1));

            if (!dict.ContainsKey(moduleName))
                dict[moduleName] = new ModuleInfo { Name = moduleName };

            if (impl.Equals("Core", StringComparison.OrdinalIgnoreCase))
            {
                dict[moduleName].CorePath = rawPath;
            }
            else
            {
                dict[moduleName].Implementations.Add(impl);
                dict[moduleName].ImplementationPaths[impl] = rawPath;
            }
        }

        foreach (var m in dict.Values)
        {
            if (m.Implementations.Count > 0 && string.IsNullOrEmpty(m.SelectedImplementation))
                m.SelectedImplementation = m.Implementations.First();
        }

        return dict.Values.OrderBy(m => m.Name).ToList();
    }

    // --- ГЕНЕРАЦИЯ AutoGenerated.targets ---
    static void GenerateTargetsFile(string solutionRoot, List<ModuleInfo> modules)
{
    string targetsPath = Path.Combine(solutionRoot, "AutoGenerated.targets");
    // Нам нужно найти файл .slnx, чтобы прочитать список проектов MyGame
    string slnxPath = Directory.GetFiles(solutionRoot, "*.slnx").FirstOrDefault() 
                      ?? throw new FileNotFoundException("SLNX file not found");

    XNamespace ns = "http://schemas.microsoft.com/developer/msbuild/2003";
    
    var doc = new XDocument(new XElement(ns + "Project"));
    var root = doc.Root;

    // Группы ссылок
    var itemGroup = new XElement(ns + "ItemGroup");
    var manualCopyGroup = new XElement(ns + "ItemGroup"); // Для плагинов

    // ==========================================
    // ЧАСТЬ 1: УПРАВЛЯЕМЫЕ МОДУЛИ (из UI)
    // ==========================================
    foreach (var m in modules)
    {
        if (!m.IsEnabled) continue;

        // Core
        if (!string.IsNullOrEmpty(m.CorePath))
        {
            string cond = GetConditionFromPath(m.CorePath);
            var refEl = new XElement(ns + "ProjectReference", 
                new XAttribute("Include", $"$(MSBuildThisFileDirectory){m.CorePath}"));
            if(!string.IsNullOrEmpty(cond)) refEl.Add(new XAttribute("Condition", cond));
            itemGroup.Add(refEl);
        }

        // Implementation (Plugin)
        if (!string.IsNullOrEmpty(m.SelectedImplementation) &&
            m.ImplementationPaths.TryGetValue(m.SelectedImplementation, out string? projPath))
        {
            string cond = GetConditionFromPath(projPath);
            string fullPath = $"$(MSBuildThisFileDirectory){projPath}";

            var refEl = new XElement(ns + "ProjectReference", new XAttribute("Include", fullPath));
            refEl.Add(new XElement(ns + "ExcludeAssets", "compile"));
            refEl.Add(new XElement(ns + "Private", "false"));
            if(!string.IsNullOrEmpty(cond)) refEl.Add(new XAttribute("Condition", cond));
            itemGroup.Add(refEl);

            var copyEl = new XElement(ns + "PluginToCopy", new XAttribute("Include", fullPath));
            if(!string.IsNullOrEmpty(cond)) copyEl.Add(new XAttribute("Condition", cond));
            manualCopyGroup.Add(copyEl);
        }
    }

    // ==========================================
    // ЧАСТЬ 2: АВТО-ПОДКЛЮЧЕНИЕ MYGAME (Без UI)
    // ==========================================
    var slnxDoc = XDocument.Load(slnxPath);
    var myGameProjects = slnxDoc.Descendants("Project")
                                .Select(p => p.Attribute("Path")?.Value)
                                .Where(p => !string.IsNullOrEmpty(p) && 
                                            p.Replace('\\', '/').StartsWith("MyGame/", StringComparison.OrdinalIgnoreCase));

    foreach (var rawPath in myGameProjects)
    {
        // Это обычные проекты, подключаем их как стандартные зависимости
        // Но обязательно применяем фильтр Client/Server
        string cond = GetConditionFromPath(rawPath!);
        
        var refEl = new XElement(ns + "ProjectReference", 
            new XAttribute("Include", $"$(MSBuildThisFileDirectory){rawPath}"));
        
        if (!string.IsNullOrEmpty(cond)) 
        {
            refEl.Add(new XAttribute("Condition", cond));
        }

        itemGroup.Add(refEl);
    }

    root!.Add(itemGroup);
    root!.Add(manualCopyGroup);

    // ==========================================
    // ЧАСТЬ 3: ОЧИСТКА И КОПИРОВАНИЕ (Без изменений)
    // ==========================================
    // (Копируйте этот блок из предыдущего рабочего варианта с CollectPluginsForTransitiveCopy)
    // Я приведу его здесь сокращенно, чтобы код был цельным.
    
    // 3.1 Transitive Copy Logic
    var targetCollect = new XElement(ns + "Target",
        new XAttribute("Name", "CollectPluginsForTransitiveCopy"),
        new XAttribute("BeforeTargets", "AssignTargetPaths;GetCopyToOutputDirectoryItems")
    );
    var msbuildTask = new XElement(ns + "MSBuild",
        new XAttribute("Projects", "@(PluginToCopy)"),
        new XAttribute("Targets", "GetTargetPath"), 
        new XAttribute("Properties", "Configuration=$(Configuration);Platform=$(Platform)")
    );
    msbuildTask.Add(new XElement(ns + "Output", new XAttribute("TaskParameter", "TargetOutputs"), new XAttribute("ItemName", "_DetectedPluginDlls")));
    targetCollect.Add(msbuildTask);

    var contentGroup = new XElement(ns + "ItemGroup");
    var contentItem = new XElement(ns + "Content", new XAttribute("Include", "@(_DetectedPluginDlls)"));
    contentItem.Add(new XElement(ns + "Link", "%(Filename)%(Extension)"));
    contentItem.Add(new XElement(ns + "CopyToOutputDirectory", "PreserveNewest"));
    contentItem.Add(new XElement(ns + "CopyToPublishDirectory", "PreserveNewest"));
    contentItem.Add(new XElement(ns + "Visible", "false"));
    contentGroup.Add(contentItem);
    targetCollect.Add(contentGroup);

    root.Add(targetCollect);

    doc.Save(targetsPath);
}

    // Хелпер для Client/Server разделения
    static string GetConditionFromPath(string path)
    {
        string normalized = path.Replace('\\', '/');
        if (normalized.IndexOf("/Client/", StringComparison.OrdinalIgnoreCase) >= 0) return "'$(IsClient)' == 'true'";
        if (normalized.IndexOf("/Server/", StringComparison.OrdinalIgnoreCase) >= 0) return "'$(IsServer)' == 'true'";
        return "";
    }


    // --- UI И ВЗАИМОДЕЙСТВИЕ ---
    static void RunUI(List<ModuleInfo> modules, string slnxPath, string propsPath, string rootPath)
    {
        int selectedIndex = 0;
        bool running = true;

        while (running)
        {
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine($"PROJECT CONFIGURATOR | Solution: {Path.GetFileName(slnxPath)}");
            Console.WriteLine("--------------------------------------------------");
            Console.WriteLine(
                "[↑/↓]: Навигация | [SPACE]: Вкл/Выкл | [ENTER]: Смена Impl | [S]: Сохранить | [Q]: Выход");
            Console.WriteLine("--------------------------------------------------\n");

            for (int i = 0; i < modules.Count; i++)
            {
                var m = modules[i];
                bool isSelected = (i == selectedIndex);

                Console.ForegroundColor = isSelected ? ConsoleColor.Yellow : ConsoleColor.Gray;
                Console.Write(isSelected ? " > " : "   ");

                string check = m.IsEnabled ? "[x]" : "[ ]";
                Console.Write($"{check} ");

                Console.ForegroundColor = m.IsEnabled ? ConsoleColor.White : ConsoleColor.DarkGray;
                Console.Write($"{m.Name.PadRight(30)}");

                if (m.Implementations.Any())
                {
                    Console.ForegroundColor = m.IsEnabled ? ConsoleColor.Green : ConsoleColor.DarkGray;
                    Console.Write($" Impl: < {m.SelectedImplementation} >");
                }
                else
                {
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    Console.Write(" (Core Only)");
                }

                Console.WriteLine();
            }

            Console.ResetColor();

            var key = Console.ReadKey(true).Key;
            switch (key)
            {
                case ConsoleKey.UpArrow:
                    selectedIndex = Math.Max(0, selectedIndex - 1);
                    break;
                case ConsoleKey.DownArrow:
                    selectedIndex = Math.Min(modules.Count - 1, selectedIndex + 1);
                    break;
                case ConsoleKey.Spacebar:
                    modules[selectedIndex].IsEnabled = !modules[selectedIndex].IsEnabled;
                    break;
                case ConsoleKey.Enter:
                    var mod = modules[selectedIndex];
                    if (mod.Implementations.Count > 0)
                    {
                        int currentIdx = mod.Implementations.IndexOf(mod.SelectedImplementation);
                        mod.SelectedImplementation = mod.Implementations[(currentIdx + 1) % mod.Implementations.Count];
                    }

                    break;
                case ConsoleKey.S:
                    SaveConfig(propsPath, modules); // Сохраняем настройки
                    GenerateTargetsFile(rootPath, modules); // Генерируем билд-скрипт
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.WriteLine("\n[SUCCESS] Конфигурация и AutoGenerated.targets обновлены!");
                    Thread.Sleep(1000);
                    break;
                case ConsoleKey.Q:
                case ConsoleKey.Escape:
                    running = false;
                    break;
            }
        }
    }

    // --- РАБОТА С DIRECTORY.BUILD.PROPS ---
    static void LoadConfig(string propsPath, List<ModuleInfo> modules)
    {
        if (!File.Exists(propsPath)) return;
        try
        {
            var doc = XDocument.Load(propsPath);
            // Ищем только нашу группу
            var propGroup = doc.Descendants("PropertyGroup")
                .FirstOrDefault(e => e.Attribute("Label")?.Value == CONFIG_LABEL);
            if (propGroup == null) return;

            foreach (var m in modules)
            {
                string cleanName = m.Name.Replace(".", "");
                var enabledEl = propGroup.Element($"Enable{cleanName}");
                if (enabledEl != null && bool.TryParse(enabledEl.Value, out bool val)) m.IsEnabled = val;

                var implEl = propGroup.Element($"Impl{cleanName}");
                if (implEl != null && m.Implementations.Contains(implEl.Value)) m.SelectedImplementation = implEl.Value;
            }
        }
        catch
        {
        }
    }

    static void SaveConfig(string propsPath, List<ModuleInfo> modules)
    {
        XDocument doc;
        if (File.Exists(propsPath))
            doc = XDocument.Load(propsPath, LoadOptions.PreserveWhitespace);
        else
            doc = new XDocument(new XElement("Project", new XElement("PropertyGroup")));

        var root = doc.Root ?? new XElement("Project");
        if (doc.Root == null) doc.Add(root);

        var configGroup = root.Elements("PropertyGroup")
            .FirstOrDefault(e => e.Attribute("Label")?.Value == CONFIG_LABEL);

        if (configGroup == null)
        {
            root.Add(new XText("\r\n  "));
            configGroup = new XElement("PropertyGroup");
            configGroup.SetAttributeValue("Label", CONFIG_LABEL);
            root.Add(configGroup);
            root.Add(new XText("\r\n"));
        }

        configGroup.RemoveNodes(); // Очищаем только наш блок

        foreach (var m in modules)
        {
            string cleanName = m.Name.Replace(".", "");

            // Ручное форматирование для красоты XML
            configGroup.Add(new XText("\r\n    "));
            configGroup.Add(new XElement($"Enable{cleanName}", m.IsEnabled.ToString().ToLower()));

            if (m.Implementations.Any())
            {
                configGroup.Add(new XText("\r\n    "));
                configGroup.Add(new XElement($"Impl{cleanName}", m.SelectedImplementation));
            }
        }

        configGroup.Add(new XText("\r\n  "));

        doc.Save(propsPath);
    }

    static string? FindSolutionRoot(string startPath)
    {
        var dir = new DirectoryInfo(startPath);
        while (dir != null)
        {
            if (dir.GetFiles("*.slnx").Any()) return dir.FullName;
            dir = dir.Parent;
        }

        return null;
    }
}